# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_name', models.CharField(max_length=30)),
                ('subtitle', models.CharField(max_length=100)),
                ('cover_image_url', models.URLField()),
                ('publish_date', models.DateField()),
                ('view_count', models.IntegerField()),
                ('article_url', models.URLField()),
            ],
        ),
    ]
